# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 04:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawls', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crawl',
            options={'ordering': ('reg_date',)},
        ),
        migrations.RenameField(
            model_name='crawl',
            old_name='linenos',
            new_name='random',
        ),
        migrations.RenameField(
            model_name='crawl',
            old_name='created',
            new_name='reg_date',
        ),
        migrations.RemoveField(
            model_name='crawl',
            name='code',
        ),
        migrations.RemoveField(
            model_name='crawl',
            name='language',
        ),
        migrations.RemoveField(
            model_name='crawl',
            name='style',
        ),
        migrations.RemoveField(
            model_name='crawl',
            name='title',
        ),
        migrations.AddField(
            model_name='crawl',
            name='crawl_type',
            field=models.CharField(choices=[('all', 'all'), ('tags', 'tags')], default='all', max_length=5),
        ),
        migrations.AddField(
            model_name='crawl',
            name='env',
            field=models.CharField(choices=[('pro', 'pro'), ('dev', 'dev'), ('test', 'test')], default='pro', max_length=5),
        ),
        migrations.AddField(
            model_name='crawl',
            name='number',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='crawl',
            name='query',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='crawl',
            name='sns_kind',
            field=models.CharField(choices=[('in', 'instagram'), ('in', 'facebook')], default='in', max_length=2),
        ),
    ]
